package model;

// Generated 2014-03-29 15:18:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * KlasaHasPrzedmiot generated by hbm2java
 */
public class KlasaHasPrzedmiot implements java.io.Serializable {

	private Integer klasaHasPrzedmiotId;
	private Przedmiot przedmiot;
	private Klasa klasa;
	private Set<Oceny> ocenies = new HashSet<Oceny>(0);

	public KlasaHasPrzedmiot() {
	}

	public KlasaHasPrzedmiot(Przedmiot przedmiot, Klasa klasa) {
		this.przedmiot = przedmiot;
		this.klasa = klasa;
	}

	public KlasaHasPrzedmiot(Przedmiot przedmiot, Klasa klasa,
			Set<Oceny> ocenies) {
		this.przedmiot = przedmiot;
		this.klasa = klasa;
		this.ocenies = ocenies;
	}

	public Integer getKlasaHasPrzedmiotId() {
		return this.klasaHasPrzedmiotId;
	}

	public void setKlasaHasPrzedmiotId(Integer klasaHasPrzedmiotId) {
		this.klasaHasPrzedmiotId = klasaHasPrzedmiotId;
	}

	public Przedmiot getPrzedmiot() {
		return this.przedmiot;
	}

	public void setPrzedmiot(Przedmiot przedmiot) {
		this.przedmiot = przedmiot;
	}

	public Klasa getKlasa() {
		return this.klasa;
	}

	public void setKlasa(Klasa klasa) {
		this.klasa = klasa;
	}

	public Set<Oceny> getOcenies() {
		return this.ocenies;
	}

	public void setOcenies(Set<Oceny> ocenies) {
		this.ocenies = ocenies;
	}

}
