package model;

// Generated 2014-03-29 15:18:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Klasa generated by hbm2java
 */
public class Klasa implements java.io.Serializable {

	private Integer idKlasa;
	private Nauczyciel nauczyciel;
	private String nazwa;
	private Date rozpoczecie;
	private Date zakonczenie;
	private Set<KlasaHasPrzedmiot> klasaHasPrzedmiots = new HashSet<KlasaHasPrzedmiot>(
			0);
	private Set<Uczen> uczens = new HashSet<Uczen>(0);

	public Klasa() {
	}

	public Klasa(String nazwa, Date rozpoczecie, Date zakonczenie) {
		this.nazwa = nazwa;
		this.rozpoczecie = rozpoczecie;
		this.zakonczenie = zakonczenie;
	}

	public Klasa(Nauczyciel nauczyciel, String nazwa, Date rozpoczecie,
			Date zakonczenie, Set<KlasaHasPrzedmiot> klasaHasPrzedmiots,
			Set<Uczen> uczens) {
		this.nauczyciel = nauczyciel;
		this.nazwa = nazwa;
		this.rozpoczecie = rozpoczecie;
		this.zakonczenie = zakonczenie;
		this.klasaHasPrzedmiots = klasaHasPrzedmiots;
		this.uczens = uczens;
	}

	public Integer getIdKlasa() {
		return this.idKlasa;
	}

	public void setIdKlasa(Integer idKlasa) {
		this.idKlasa = idKlasa;
	}

	public Nauczyciel getNauczyciel() {
		return this.nauczyciel;
	}

	public void setNauczyciel(Nauczyciel nauczyciel) {
		this.nauczyciel = nauczyciel;
	}

	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	public Date getRozpoczecie() {
		return this.rozpoczecie;
	}

	public void setRozpoczecie(Date rozpoczecie) {
		this.rozpoczecie = rozpoczecie;
	}

	public Date getZakonczenie() {
		return this.zakonczenie;
	}

	public void setZakonczenie(Date zakonczenie) {
		this.zakonczenie = zakonczenie;
	}

	public Set<KlasaHasPrzedmiot> getKlasaHasPrzedmiots() {
		return this.klasaHasPrzedmiots;
	}

	public void setKlasaHasPrzedmiots(Set<KlasaHasPrzedmiot> klasaHasPrzedmiots) {
		this.klasaHasPrzedmiots = klasaHasPrzedmiots;
	}

	public Set<Uczen> getUczens() {
		return this.uczens;
	}

	public void setUczens(Set<Uczen> uczens) {
		this.uczens = uczens;
	}

}
