package model;

// Generated 2014-03-29 15:18:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nauczyciel generated by hbm2java
 */
public class Nauczyciel implements java.io.Serializable {

	private Integer idNauczyciel;
	private String imie;
	private String nazwisko;
	private String pesel;
	private String haslo;
	private Set<Klasa> klasas = new HashSet<Klasa>(0);
	private Set<Przedmiot> przedmiots = new HashSet<Przedmiot>(0);

	public Nauczyciel() {
	}

	public Nauczyciel(String imie, String nazwisko, String pesel, String haslo) {
		this.imie = imie;
		this.nazwisko = nazwisko;
		this.pesel = pesel;
		this.haslo = haslo;
	}

	public Nauczyciel(String imie, String nazwisko, String pesel, String haslo,
			Set<Klasa> klasas, Set<Przedmiot> przedmiots) {
		this.imie = imie;
		this.nazwisko = nazwisko;
		this.pesel = pesel;
		this.haslo = haslo;
		this.klasas = klasas;
		this.przedmiots = przedmiots;
	}

	public Integer getIdNauczyciel() {
		return this.idNauczyciel;
	}

	public void setIdNauczyciel(Integer idNauczyciel) {
		this.idNauczyciel = idNauczyciel;
	}

	public String getImie() {
		return this.imie;
	}

	public void setImie(String imie) {
		this.imie = imie;
	}

	public String getNazwisko() {
		return this.nazwisko;
	}

	public void setNazwisko(String nazwisko) {
		this.nazwisko = nazwisko;
	}

	public String getPesel() {
		return this.pesel;
	}

	public void setPesel(String pesel) {
		this.pesel = pesel;
	}

	public String getHaslo() {
		return this.haslo;
	}

	public void setHaslo(String haslo) {
		this.haslo = haslo;
	}

	public Set<Klasa> getKlasas() {
		return this.klasas;
	}

	public void setKlasas(Set<Klasa> klasas) {
		this.klasas = klasas;
	}

	public Set<Przedmiot> getPrzedmiots() {
		return this.przedmiots;
	}

	public void setPrzedmiots(Set<Przedmiot> przedmiots) {
		this.przedmiots = przedmiots;
	}

}
