package model;

// Generated 2014-03-29 15:18:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Oceny generated by hbm2java
 */
public class Oceny implements java.io.Serializable {

	private Integer idOceny;
	private Uczen uczen;
	private KlasaHasPrzedmiot klasaHasPrzedmiot;
	private int wartosc;
	private Integer waga;
	private Date dataWstawienia;
	private String komentarz;

	public Oceny() {
	}

	public Oceny(Uczen uczen, KlasaHasPrzedmiot klasaHasPrzedmiot, int wartosc) {
		this.uczen = uczen;
		this.klasaHasPrzedmiot = klasaHasPrzedmiot;
		this.wartosc = wartosc;
	}

	public Oceny(Uczen uczen, KlasaHasPrzedmiot klasaHasPrzedmiot, int wartosc,
			Integer waga, Date dataWstawienia, String komentarz) {
		this.uczen = uczen;
		this.klasaHasPrzedmiot = klasaHasPrzedmiot;
		this.wartosc = wartosc;
		this.waga = waga;
		this.dataWstawienia = dataWstawienia;
		this.komentarz = komentarz;
	}

	public Integer getIdOceny() {
		return this.idOceny;
	}

	public void setIdOceny(Integer idOceny) {
		this.idOceny = idOceny;
	}

	public Uczen getUczen() {
		return this.uczen;
	}

	public void setUczen(Uczen uczen) {
		this.uczen = uczen;
	}

	public KlasaHasPrzedmiot getKlasaHasPrzedmiot() {
		return this.klasaHasPrzedmiot;
	}

	public void setKlasaHasPrzedmiot(KlasaHasPrzedmiot klasaHasPrzedmiot) {
		this.klasaHasPrzedmiot = klasaHasPrzedmiot;
	}

	public int getWartosc() {
		return this.wartosc;
	}

	public void setWartosc(int wartosc) {
		this.wartosc = wartosc;
	}

	public Integer getWaga() {
		return this.waga;
	}

	public void setWaga(Integer waga) {
		this.waga = waga;
	}

	public Date getDataWstawienia() {
		return this.dataWstawienia;
	}

	public void setDataWstawienia(Date dataWstawienia) {
		this.dataWstawienia = dataWstawienia;
	}

	public String getKomentarz() {
		return this.komentarz;
	}

	public void setKomentarz(String komentarz) {
		this.komentarz = komentarz;
	}

}
