package model;

// Generated 2014-03-29 15:18:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Przedmiot generated by hbm2java
 */
public class Przedmiot implements java.io.Serializable {

	private Integer idPrzedmiot;
	private Nauczyciel nauczyciel;
	private String nazwa;
	private Set<KlasaHasPrzedmiot> klasaHasPrzedmiots = new HashSet<KlasaHasPrzedmiot>(
			0);

	public Przedmiot() {
	}

	public Przedmiot(Nauczyciel nauczyciel, String nazwa) {
		this.nauczyciel = nauczyciel;
		this.nazwa = nazwa;
	}

	public Przedmiot(Nauczyciel nauczyciel, String nazwa,
			Set<KlasaHasPrzedmiot> klasaHasPrzedmiots) {
		this.nauczyciel = nauczyciel;
		this.nazwa = nazwa;
		this.klasaHasPrzedmiots = klasaHasPrzedmiots;
	}

	public Integer getIdPrzedmiot() {
		return this.idPrzedmiot;
	}

	public void setIdPrzedmiot(Integer idPrzedmiot) {
		this.idPrzedmiot = idPrzedmiot;
	}

	public Nauczyciel getNauczyciel() {
		return this.nauczyciel;
	}

	public void setNauczyciel(Nauczyciel nauczyciel) {
		this.nauczyciel = nauczyciel;
	}

	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	public Set<KlasaHasPrzedmiot> getKlasaHasPrzedmiots() {
		return this.klasaHasPrzedmiots;
	}

	public void setKlasaHasPrzedmiots(Set<KlasaHasPrzedmiot> klasaHasPrzedmiots) {
		this.klasaHasPrzedmiots = klasaHasPrzedmiots;
	}

}
