package model;

// Generated 2014-04-01 13:32:49 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SchoolClass generated by hbm2java
 */
public class SchoolClass implements java.io.Serializable {

	private Integer idSchoolClass;
	private Teacher teacher;
	private String name;
	private Date yearStart;
	private Date yearEnd;
	private Set<Subject> subjects = new HashSet<Subject>(0);
	private Set<Student> students = new HashSet<Student>(0);

	public SchoolClass() {
	}

	public SchoolClass(Teacher teacher, String name, Date yearStart,
			Date yearEnd) {
		this.teacher = teacher;
		this.name = name;
		this.yearStart = yearStart;
		this.yearEnd = yearEnd;
	}

	public SchoolClass(Teacher teacher, String name, Date yearStart,
			Date yearEnd, Set<Subject> subjects, Set<Student> students) {
		this.teacher = teacher;
		this.name = name;
		this.yearStart = yearStart;
		this.yearEnd = yearEnd;
		this.subjects = subjects;
		this.students = students;
	}

	public Integer getIdSchoolClass() {
		return this.idSchoolClass;
	}

	public void setIdSchoolClass(Integer idSchoolClass) {
		this.idSchoolClass = idSchoolClass;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getYearStart() {
		return this.yearStart;
	}

	public void setYearStart(Date yearStart) {
		this.yearStart = yearStart;
	}

	public Date getYearEnd() {
		return this.yearEnd;
	}

	public void setYearEnd(Date yearEnd) {
		this.yearEnd = yearEnd;
	}

	public Set<Subject> getSubjects() {
		return this.subjects;
	}

	public void setSubjects(Set<Subject> subjects) {
		this.subjects = subjects;
	}

	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
