package model;

// Generated 2014-04-01 13:32:49 by Hibernate Tools 4.0.0

/**
 * StudentNote generated by hbm2java
 */
public class StudentNote implements java.io.Serializable {

	private Integer idStudentNote;
	private Teacher teacher;
	private Student student;
	private String noteContents;

	public StudentNote() {
	}

	public StudentNote(Teacher teacher, Student student, String noteContents) {
		this.teacher = teacher;
		this.student = student;
		this.noteContents = noteContents;
	}

	public Integer getIdStudentNote() {
		return this.idStudentNote;
	}

	public void setIdStudentNote(Integer idStudentNote) {
		this.idStudentNote = idStudentNote;
	}

	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public String getNoteContents() {
		return this.noteContents;
	}

	public void setNoteContents(String noteContents) {
		this.noteContents = noteContents;
	}

}
