package model;

// Generated 2014-04-01 13:32:49 by Hibernate Tools 4.0.0


import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private Integer idStudent;
	private SchoolClass schoolClass;
	private String firstName;
	private String lastName;
	private String personalIdentityNumber;
	private String password;
	private Date dateOfBirth;
	private String address;
	private Set<SubjectMark> subjectMarks = new HashSet<SubjectMark>(0);
	private Set<StudentNote> studentNotes = new HashSet<StudentNote>(0);

	public Student() {
	}

	public Student(SchoolClass schoolClass, String firstName, String lastName,
			String personalIdentityNumber, String password, Date dateOfBirth,
			String address) {
		this.schoolClass = schoolClass;
		this.firstName = firstName;
		this.lastName = lastName;
		this.personalIdentityNumber = personalIdentityNumber;
		this.password = password;
		this.dateOfBirth = dateOfBirth;
		this.address = address;
		this.subjectMarks=null;
		this.studentNotes=null;
	}

	public Student(SchoolClass schoolClass, String firstName, String lastName,
			String personalIdentityNumber, String password, Date dateOfBirth,
			String address, Set<SubjectMark> subjectMarks,
			Set<StudentNote> studentNotes) {
		this.schoolClass = schoolClass;
		this.firstName = firstName;
		this.lastName = lastName;
		this.personalIdentityNumber = personalIdentityNumber;
		this.password = password;
		this.dateOfBirth = dateOfBirth;
		this.address = address;
		this.subjectMarks = subjectMarks;
		this.studentNotes = studentNotes;
	}

	public Integer getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(Integer idStudent) {
		this.idStudent = idStudent;
	}

	public SchoolClass getSchoolClass() {
		return this.schoolClass;
	}

	public void setSchoolClass(SchoolClass schoolClass) {
		this.schoolClass = schoolClass;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPersonalIdentityNumber() {
		return this.personalIdentityNumber;
	}

	public void setPersonalIdentityNumber(String personalIdentityNumber) {
		this.personalIdentityNumber = personalIdentityNumber;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set<SubjectMark> getSubjectMarks() {
		return this.subjectMarks;
	}

	public void setSubjectMarks(Set<SubjectMark> subjectMarks) {
		this.subjectMarks = subjectMarks;
	}

	public Set<StudentNote> getStudentNotes() {
		return this.studentNotes;
	}

	public void setStudentNotes(Set<StudentNote> studentNotes) {
		this.studentNotes = studentNotes;
	}

}
