package model;

// Generated 2014-04-01 13:32:49 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * SubjectMark generated by hbm2java
 */
public class SubjectMark implements java.io.Serializable {

	private Integer idSubjectMark;
	private Date timeStamp;
	private Student student;
	private Subject subject;
	private double value;
	private int weight;
	private String description;

	public SubjectMark() {
	}

	public SubjectMark(Student student, Subject subject, double value, int weight) {
		this.student = student;
		this.subject = subject;
		this.value = value;
		this.weight = weight;
	}

	public SubjectMark(Student student, Subject subject, double value, int weight,
			String description) {
		this.student = student;
		this.subject = subject;
		this.value = value;
		this.weight = weight;
		this.description = description;
	}

	public Integer getIdSubjectMark() {
		return this.idSubjectMark;
	}

	public void setIdSubjectMark(Integer idSubjectMark) {
		this.idSubjectMark = idSubjectMark;
	}

	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
