package model;

// Generated 2014-04-01 13:32:49 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Teacher generated by hbm2java
 */
public class Teacher implements java.io.Serializable {

	private Integer idTeacher;
	private Subject subject;
	private String firstName;
	private String lastName;
	private String personalIdentityNumber;
	private String password;
	private String address;
	private Set<StudentNote> studentNotes = new HashSet<StudentNote>(0);

	public Teacher() {
	}

	public Teacher(Subject subject, String firstName, String lastName,
			String personalIdentityNumber, String password, String address) {
		this.subject = subject;
		this.firstName = firstName;
		this.lastName = lastName;
		this.personalIdentityNumber = personalIdentityNumber;
		this.password = password;
		this.address = address;
	}

	public Teacher(Subject subject, String firstName, String lastName,
			String personalIdentityNumber, String password, String address, Set<StudentNote> studentNotes) {
		this.subject = subject;
		this.firstName = firstName;
		this.lastName = lastName;
		this.personalIdentityNumber = personalIdentityNumber;
		this.password = password;
		this.address = address;
		this.studentNotes = studentNotes;
	}

	public Integer getIdTeacher() {
		return this.idTeacher;
	}

	public void setIdTeacher(Integer idTeacher) {
		this.idTeacher = idTeacher;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPersonalIdentityNumber() {
		return this.personalIdentityNumber;
	}

	public void setPersonalIdentityNumber(String personalIdentityNumber) {
		this.personalIdentityNumber = personalIdentityNumber;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}


	public Set<StudentNote> getStudentNotes() {
		return this.studentNotes;
	}

	public void setStudentNotes(Set<StudentNote> studentNotes) {
		this.studentNotes = studentNotes;
	}

}
